# 公共配置地址
base:
  auth:
    server: http://localhost:6001
  mysql:
    url: jdbc:mysql://localhost:3306
  sqlserver:
    url: jdbc:sqlserver://localhost:1433
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    #password: 123456


management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
  endpoint:
    health:
      show-details: ALWAYS

server:
  tomcat:
    max-threads: 200 # Maximum amount of worker threads.
    min-spare-threads: 10 # Minimum amount of worker threads
# jpa配置 数据源配置
spring:
  datasource:
#    url: ${base.sqlserver.url};DatabaseName=test
#    username: sa
#    password: K2pass!
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${base.mysql.url}/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: Sy-Pms-HikariCP
  #redis配置
  redis:
    host: ${base.redis.host}
    port: ${base.redis.port}
    password: ${base.redis.password}
    database: 0

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.platform.business.model.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.platform.business.mapper: debug

sy:
  # swagger2配置
  swagger:
    enabled: true
    title: Sy 后台管理
    description: Sy 后台管理 RestFull Api
    version: 1.0.1-SNAPSHOT
    license: Apache License, Version 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html
    terms-of-service-url: https://sy.com/
    contact:
      name: sy
      url: https://sy.com/
      email: sy@sy.com
    base-package: com.platform.business.controller
    base-path: /**
    exclude-path: /error